name: machinemem
channels:
- pytorch
- defaults
dependencies:
- python=3.7.7
- pytorch=1.7.1
- torchvision=0.8.2
- scipy
- pip:
  - Pillow==6.1.0
  - numpy==1.16.4
  - opencv-python ==3.4.2.17
  - timm == 0.5.4
  - scikit-learn == 1.0.1
